CREATE TABLE `heroe` (
`id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`slug` VARCHAR(100),
`image_sm` VARCHAR(255) NOT NULL,
`image_md` VARCHAR(255) NOT NULL,
`gender` VARCHAR(100) NOT NULL,
`race` VARCHAR(100),
`eyeColor` VARCHAR(100) NOT NULL,
`hairColor` VARCHAR(100) NOT NULL,
`fullName` VARCHAR(100),
`placeOfBirth` VARCHAR(100),
`firstAppearance` VARCHAR(200) NOT NULL,
`work` VARCHAR(200) NOT NULL,
`intelligence` INT,
`strength` INT,
`speed` INT,
`durability` INT,
`power` INT,
`combat` INT,
PRIMARY KEY (`id`)
);

INSERT INTO `heroe` (name, slug, image_sm, image_md, gender,race, eyeColor, hairColor, fullName, placeOfBirth, firstAppearance,work, intelligence, strength, speed, durability, power, combat )
VALUES ('A-Bomb', '1-a-bomb', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/1-a-bomb.jpg', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/1-a-bomb.jpg', 'Male', 'Human', 'Yellow', 'No Hair' , 'Richard Milhouse Jones', 'Scarsdale, Arizona', 'Hulk Vol 2 #2 (April, 2008) (as A-Bomb)', 'Musician, adventurer, author; formerly talk show host', 38, 100, 17, 80, 24, 64),
("Abe Sapien", "2-abe-sapien","https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/2-abe-sapien.jpg", 
"https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/2-abe-sapien.jpg",
"Male", "Icthyo Sapien","Blue","No Hair","Abraham Sapien","-","Hellboy: Seed of Destruction (1993)","Paranormal Investigator",88, 28, 35, 65, 100, 85),
(
 'Abin Sur',
 '3-abin-sur',
 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/3-abin-sur.jpg',
 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/3-abin-sur.jpg',
 'Male',
 'Ungaran',
 'Blue',
  'No Hair',
  '',
   'Ungara',
   'Showcase #22 (October, 1959)',
   'Green Lantern, former history professor',
   50,
   90,
   53,
   64,
   99,
   65
  ),
  ('Abomination', '4-abomination', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/4-abomination.jpg', 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/4-abomination.jpg', 'Male', 'Human / Radiation', 'Green', 'No Hair', 'Emil Blonsky', 'Zagreb, Yugoslavia', 'Tales to Astonish #90', 'Ex-Spy', 63, 80, 53, 90, 62, 95);