name: main

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    permissions:
      checks: write
      contents: write

  
